### ISSUE TITLE
Question: Azurite + AzureEventGridSimulator

### ISSUE THREAD

**Issue by poul-kg** [pmcilreavy/AzureEventGridSimulator#14]
Hello this is not an issue but a question:

I saw this article: https://docs.microsoft.com/en-us/azure/event-grid/blob-event-quickstart-portal#subscribe-to-the-blob-storage

and I have this running in the cloud. But I want to simulate it locally.

`Azure Blob Storage Emulator (on file upload) ---> Event Grid Simulator ---> run local cloud function`

I emulate Azure Blob Storage via [Azurite](https://github.com/Azure/Azurite), I know there is also [Azure Blob Storage Emulator](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator)

as far as I understand, I need to call some `localhost:port` endpoint in your AzureEventGridSimulator manually and supply my pre-recorded event. Is there some easy way how to send events from Azure Blobl Storage emulator to AzureEventGridSimulator?

Did you ever had similar use cases or this is not a good approach?

**Comment by pmcilreavy** [comment]
Hi, not sure of a way around this. ngrok could be a useful tool to redirect events from the cloud to your localhost though.

Trying to recreate this much of Azure locally might not be the best approach though. If you are simulating this whole pipeline then what are you actually testing at this point? Feels like you'd be testing that the simulators are working rather than your own code. Probably better to just test a specific scenario using pre-crafted inputs and outputs.

**Comment by poul-kg** [comment]
@pmcilreavy thank you for your answer!

> If you are simulating this whole pipeline then what are you actually testing at this point?
it's more like end to end tests, but I wanted to move as much of a cloud infrastructure to local machine as possible. Maybe it's not a good idea, maybe it's better to run the stuff in the cloud, as it's end to end and not unit test.
