### ISSUE TITLE
Getting "a Task was cancelled" error when publishing event with Azure.Messaging.EventGrid client

### ISSUE THREAD

**Issue by Saaman** [pmcilreavy/AzureEventGridSimulator#39]
In my context, I'm using `EventGridPublisherClient` from Azure.Messaging.EventGrid package to publish events to the simulator.
It works fine, except that I got a "A task was cancelled" error. Considering the retry logic I configured on that client, I end up having each one of my events being handled 3 times in a row.

It seems to come from this line: 
https://github.com/pmcilreavy/AzureEventGridSimulator/blob/5325b4b2b0c33719234851c5264f6c94c90d83a4/src/AzureEventGridSimulator/Domain/Commands/SendNotificationEventsToSubscriberCommandHandler.cs#L66

Why not waiting for the ` SendToSubscriber` call to be completed with `await`?

As a temporary fix, here is what I did: 
```csharp
var sendToSubscriberTasks = request.Topic.Subscribers
             Select(x => SendToSubscriber(x, request.Events, request.Topic.Name));
await Task.WhenAll(sendToSubscriberTasks);
```

**Comment by pmcilreavy** [comment]
Hi, we do not await the delivery of requests to the subscribers because the real Azure Event Grid does not do this. When a message is published to the real Event Grid a 200 OK message is returned immediately. It does not wait for the event(s) to be published to the subscribers. Once the event has been received it will dispatch the event to each subscriber. If an event fails to be sent to a subscriber then only that subscriber will be retried. Subscriber retry settings are not implemented in the simulator - although we may do this in future. The retry settings you refer to in the Azure.Messaging.EventGrid client is related to the publishing of the message to the event grid only and is not related to the subscriber retries.

It sounds like maybe when you published an event one of your subscribers was not configured correctly or maybe was not running and so that resulted in you seeing an error in the simulator console and you would have received a 200 OK response? This is the expected behaviour. Adding `await` in your fix above will only cause the publishing of the message to also fail which is not the behaviour that the real Event Grid has and so this is not a 'fix'. If I am misunderstanding the issue though please let me know.

**Comment by Saaman** [comment]
Thank you for your quick answer!
It explained a lot, I understand why the subscribers calls are not awaited, it makes sense.

It turns out my issue happens only from time to time. My subscriber is well configured and is always working properly, the issue is more with my publisher. Sometimes the publication gets "jammed" for no reason, the publisher got its connection killed.
I'll dig deeper on my side see if I can find anything. I'll keep you posted in case it is related to the Simulator.
Thank you for the great work, it's really a key component to easily develop on my local machine!
